# ç½‘ç«™æ ‡é¢˜
logo_title: è¿›å‡»ã®ç®—æ³•
# åˆå§‹åŒ–é£æ ¼ black/light
style: light

#SEOä¼˜åŒ–

## ç½‘ç«™æè¿°
description: å˜¿ï¼Œæˆ‘æ˜¯åˆ˜è®­ç¼ï½è¿™æ˜¯æˆ‘çš„å­ç«™ï¼Œç”¨äºå±•ç¤ºå†™çš„Hexoä¸»é¢˜ï¼šCoderã€‚æ¬¢è¿è®¿é—®ï¼

## ç½‘ç«™å…³é”®è¯ï¼šç”¨è‹±æ–‡é€—å·åˆ†å‰²
keywords: Blog,Hexo,Theme,åˆ˜è®­ç¼,LiuXunzhuo

# é¦–é¡µURL
link: https://www.liuxunzhuo.top

#æ ‡è¯­:
words: AI ğŸ¤–ï¸ Code ğŸ§‘â€ğŸ’» Life ğŸŒˆ

# ä½ çš„æ˜µç§°
author: LiuXunzhuo
# ä¸­å¿ƒå›¾æ ‡é€‰æ‹©ç”·å¥³æˆ–è€…è‡ªå®šä¹‰
gender: /img/male.png #/img/female.png

favicon: /img/favicon.ico

# èœå•æ é…ç½®
menu:
  å…³äºæˆ‘ğŸ‘€: /about
  è®¿é—®ä¸»ç«™ğŸ‰: https://liuxunzhuo.tech
  GitHubğŸ’: https://github.com/xunzhuo

# åšäº†åŸŸåé™åˆ¶ï¼Œè¯·æ”¹æˆè‡ªå·±çš„ KEY
# è‹¥å…³é—­valine è®¾ç½®enableä¸ºfalseâˆ‚
valine:
  enable: true
  appId: NOsswOncKgc8HOxqo9oxIWlX-gzGzoHsz
  appKey: z1FihjWEbS8uIfUQdmCtK7zz


highlight:
  enable: true