# å½“å‰ç‰ˆæœ¬ | Theme Version
Hexo: "1.2"

# ç½‘ç«™æ ‡é¢˜ | Title
logo_title: Title_Name

# åˆå§‹åŒ–é£æ ¼ | Default Style "black/light"
style: black
#style: light

# é¦–é¡µURL | Your URL
link: Your_URL

#æ ‡è¯­ | Your Slogan
words: Your Words

# ä½ çš„æ˜µç§° | Your Name
author: Your Name

# ä¸­å¿ƒå›¾æ ‡é€‰æ‹©ç”·å¥³æˆ–è€…è‡ªå®šä¹‰ | Gender
gender: /img/male.png #/img/female.png

# ç«™ç‚¹å°å›¾æ ‡åœ°å€ | Small Icon of Your Site
favicon: /img/favicon.ico

# èœå•æ é…ç½® | Nav Bar Settings
menu:
  å…³äºæˆ‘ğŸ‘€: /about
  è®¿é—®ä¸»ç«™ğŸ‰: https://liuxunzhuo.tech
  GitHubğŸ’: https://github.com/xunzhuo

# ç«™å†…å…³é”®è¯æœç´¢ | Local Search
## è¯·éœ€å…ˆå®‰è£…å¯¹åº”æ’ä»¶ | You need to insatall the following plugin
## https://github.com/PaicHyperionDev/hexo-generator-search
## $ npm install hexo-generator-search --save
#search:
 # enable: true
 # path: search.xml
 # ield: post
 # content: true
 # onload: true

# è¯„è®ºç³»ç»Ÿ | Comments
## åšäº†åŸŸåé™åˆ¶ï¼Œè¯·æ”¹æˆè‡ªå·±çš„ KEY
## è‹¥å…³é—­valine è®¾ç½®enableä¸ºfalseâˆ‚
valine:
  enable: true
  appId: NOsswOncKgc8HOxqo9oxIWlX-gzGzoHsz
  appKey: z1FihjWEbS8uIfUQdmCtK7zz


highlight:
  enable: true